In [3]:
#Importando bibliotecas
import pandas as pd

In [5]:
#Chamada do arquivo .csv
df_vendas = pd.read_csv(r'c:\Users\USER\Desktop\python\bd_vendas-registroVendas.csv')

In [6]:
#Pré-visualização do arquivo
df_vendas

,ID Pedido,Data Pedido,Código Loja,Produto,Qtde/Preco Unit,Pagamento
0,AX04,1/1/2023,A1500108,Carteira,23/210,Cartão de Crédito
1,AX16,1/3/2023,A1500108,FONE,22/159,Transferência/PIX
2,AX15,1/3/2023,A1500108,Malaa,"69/499,19",Cartão de Crédito
3,AX13,1/3/2023,A1500108,Mochila,"66/630,99",Cartão de Crédito
4,AX22,1/4/2023,A1500108,Boné,"37/160,99",Cartão de Crédito
...,...,...,...,...,...,...
1950,AX5406,12/31/2023,A1500107,Garrafa,"100/119,3",Transferência/PIX
1951,AX3255,12/31/2023,A1500108,Mochila,"29/630,99",Cartão de Crédito
1952,AX5407,12/31/2023,A1500107,BOLSA,80/999,Cartão de Crédito
1953,AX5401,12/31/2023,A1500107,Tênis,"184/320,19",Cartão de Crédito
1954,AX3262,12/31/2023,A1500108,Mochila,"43/630,99",Cartão de Crédito

In [7]:
#Tratamento dos dados usando replace
df_vendas ['Produto'] = df_vendas ['Produto'].replace({
    'FONE' : 'Fone',
    'Malaa' : 'Mala',
    'BOLSA' : 'Bolsa'
})

In [8]:
#Tratamento dos dados
#Dividindo colunas unificadas
df_vendas[['Quantidade', 'Preço Unitário']] = df_vendas['Qtde/Preco Unit'].str.split('/', expand=True)

In [9]:
#Tratamento dos dados substituindo (,) por (.)
#Após a separação das colunas unificadas, os dados das mesmas foram transformados em string (texto)
#Transformando uma string (texto) em dados numéricos novamente, usando pandas (pd.to_numeric) 
df_vendas['Preço Unitário'] = (
    df_vendas['Preço Unitário'].str.replace(',', '.', regex=False))

df_vendas['Preço Unitário'] = pd.to_numeric(
    df_vendas['Preço Unitário']
)

df_vendas['Quantidade'] = pd.to_numeric(
    df_vendas['Quantidade'])

In [10]:
#Excluindo a coluna que foi  tratada
df_vendas = df_vendas.drop(columns=['Qtde/Preco Unit'])

In [11]:
#Visualização dos dados 
#Tratamento quase concluído
df_vendas

,ID Pedido,Data Pedido,Código Loja,Produto,Pagamento,Quantidade,Preço Unitário
0,AX04,1/1/2023,A1500108,Carteira,Cartão de Crédito,23,210.00
1,AX16,1/3/2023,A1500108,Fone,Transferência/PIX,22,159.00
2,AX15,1/3/2023,A1500108,Mala,Cartão de Crédito,69,499.19
3,AX13,1/3/2023,A1500108,Mochila,Cartão de Crédito,66,630.99
4,AX22,1/4/2023,A1500108,Boné,Cartão de Crédito,37,160.99
...,...,...,...,...,...,...,...
1950,AX5406,12/31/2023,A1500107,Garrafa,Transferência/PIX,100,119.30
1951,AX3255,12/31/2023,A1500108,Mochila,Cartão de Crédito,29,630.99
1952,AX5407,12/31/2023,A1500107,Bolsa,Cartão de Crédito,80,999.00
1953,AX5401,12/31/2023,A1500107,Tênis,Cartão de Crédito,184,320.19
1954,AX3262,12/31/2023,A1500108,Mochila,Cartão de Crédito,43,630.99

In [12]:
#Identificando dados negativos ou iguais a zero na coluna Quantidade e Preço Unitário.
df_vendas[(df_vendas['Quantidade'] <= 0) & (df_vendas['Preço Unitário'] <= 0)]

Empty DataFrame
Columns: [ID Pedido, Data Pedido, Código Loja, Produto, Pagamento, Quantidade, Preço Unitário]
Index: []

In [13]:
#Multiplicado colunas (Quantidade * Preço Unitário)
#Adicionando coluna de Faturamento Total
df_vendas['Faturamento Total'] = (
    df_vendas['Quantidade'] * df_vendas['Preço Unitário']
)

In [14]:
df_vendas

,ID Pedido,Data Pedido,Código Loja,Produto,Pagamento,Quantidade,Preço Unitário,Faturamento Total
0,AX04,1/1/2023,A1500108,Carteira,Cartão de Crédito,23,210.00,4830.00
1,AX16,1/3/2023,A1500108,Fone,Transferência/PIX,22,159.00,3498.00
2,AX15,1/3/2023,A1500108,Mala,Cartão de Crédito,69,499.19,34444.11
3,AX13,1/3/2023,A1500108,Mochila,Cartão de Crédito,66,630.99,41645.34
4,AX22,1/4/2023,A1500108,Boné,Cartão de Crédito,37,160.99,5956.63
...,...,...,...,...,...,...,...,...
1950,AX5406,12/31/2023,A1500107,Garrafa,Transferência/PIX,100,119.30,11930.00
1951,AX3255,12/31/2023,A1500108,Mochila,Cartão de Crédito,29,630.99,18298.71
1952,AX5407,12/31/2023,A1500107,Bolsa,Cartão de Crédito,80,999.00,79920.00
1953,AX5401,12/31/2023,A1500107,Tênis,Cartão de Crédito,184,320.19,58914.96
1954,AX3262,12/31/2023,A1500108,Mochila,Cartão de Crédito,43,630.99,27132.57

In [15]:
#Resumo estrutural dos dados
#Verificando se há dados nulos
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1955 entries, 0 to 1954
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID Pedido          1955 non-null   str
 1   Data Pedido        1955 non-null   str
 2   Código Loja        1955 non-null   str
 3   Produto            1955 non-null   str
 4   Pagamento          1955 non-null   str
 5   Quantidade         1955 non-null   int64
 6   Preço Unitário     1955 non-null   float64
 7   Faturamento Total  1955 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 122.3 KB

In [17]:
#Subistituindo a identificação de cada loja
df_vendas['Código Loja'] = df_vendas['Código Loja'].replace({
    'A3100104' : 'Filial 01 ES',
    'A1500107' : 'Matriz SP',
    'A1500108' : 'Filial 02 RJ'})

In [18]:
#Dados já tratados e prontos para análises
df_vendas

,ID Pedido,Data Pedido,Código Loja,Produto,Pagamento,Quantidade,Preço Unitário,Faturamento Total
0,AX04,1/1/2023,Filial 02 RJ,Carteira,Cartão de Crédito,23,210.00,4830.00
1,AX16,1/3/2023,Filial 02 RJ,Fone,Transferência/PIX,22,159.00,3498.00
2,AX15,1/3/2023,Filial 02 RJ,Mala,Cartão de Crédito,69,499.19,34444.11
3,AX13,1/3/2023,Filial 02 RJ,Mochila,Cartão de Crédito,66,630.99,41645.34
4,AX22,1/4/2023,Filial 02 RJ,Boné,Cartão de Crédito,37,160.99,5956.63
...,...,...,...,...,...,...,...,...
1950,AX5406,12/31/2023,Matriz SP,Garrafa,Transferência/PIX,100,119.30,11930.00
1951,AX3255,12/31/2023,Filial 02 RJ,Mochila,Cartão de Crédito,29,630.99,18298.71
1952,AX5407,12/31/2023,Matriz SP,Bolsa,Cartão de Crédito,80,999.00,79920.00
1953,AX5401,12/31/2023,Matriz SP,Tênis,Cartão de Crédito,184,320.19,58914.96
1954,AX3262,12/31/2023,Filial 02 RJ,Mochila,Cartão de Crédito,43,630.99,27132.57

In [19]:
df_vendas.describe()

        Quantidade  Preço Unitário  Faturamento Total
count  1955.000000     1955.000000        1955.000000
mean     53.086445      391.491151       20518.846527
std      36.664196      288.369041       22647.065745
min      15.000000      119.300000        1789.500000
25%      30.000000      159.000000        6514.500000
50%      42.000000      210.000000       12978.940000
75%      60.000000      630.990000       25239.600000
max     208.000000      999.000000      203796.000000

In [20]:
#Agrupando dados
#Produto mais vendido ao menos vendido por quantidade
df_vendas.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)

Produto
Carteira    14506
Mala        14211
Fone        13585
Garrafa     13287
Bolsa       12872
Mochila     12462
Tênis       11470
Boné        11391
Name: Quantidade, dtype: int64

In [21]:
#Agrupando dados
#Produto mais vendido ao menos vendido por quantidade
df_vendas.groupby('Produto', as_index=False)['Quantidade'].sum().sort_values('Quantidade',ascending=False)

    Produto  Quantidade
2  Carteira       14506
5      Mala       14211
3      Fone       13585
4   Garrafa       13287
0     Bolsa       12872
6   Mochila       12462
7     Tênis       11470
1      Boné       11391

In [22]:
#Agrupando dados
#Produto com o maior ao menor faturamento 
df_vendas.groupby('Produto', as_index=False)['Faturamento Total'].sum().sort_values('Faturamento Total', ascending=False)

    Produto  Faturamento Total
0     Bolsa        12859128.00
6   Mochila         7863397.38
5      Mala         7093989.09
7     Tênis         3672579.30
2  Carteira         3046260.00
3      Fone         2160015.00
1      Boné         1833837.09
4   Garrafa         1585139.10

In [23]:
#Agrupando dados
#Faturamento Total de cada loja
#Loja com o maior faturamento
df_vendas.groupby('Código Loja', as_index=False)['Faturamento Total'].sum().sort_values('Código Loja', ascending=False)

    Código Loja  Faturamento Total
2     Matriz SP        15990616.66
1  Filial 02 RJ        14063358.42
0  Filial 01 ES        10060369.88

In [24]:
#Identificação dos produtos mais vendidos por cada loja
vendas_loja = (df_vendas.groupby(['Código Loja', 'Produto'])['Quantidade'].sum().reset_index())

mais_vendidos = vendas_loja.loc[vendas_loja.groupby('Código Loja')['Quantidade'].idxmax('Código Loja')]

In [25]:
#Visualizanção dos produtos mais vendidos por cada loja
print(mais_vendidos)

     Código Loja   Produto  Quantidade
6   Filial 01 ES   Mochila        3769
10  Filial 02 RJ  Carteira        5497
21     Matriz SP      Mala        5750

In [26]:
#Método de pagamento mais utilizado
df_vendas['Pagamento'].value_counts().head(1)

Pagamento
Cartão de Crédito    1214
Name: count, dtype: int64

In [35]:
#Faturamento por tipo de Pagamento
faturamento_por_pagamento = (
    df_vendas.groupby('Pagamento')['Faturamento Total'].sum().reset_index().sort_values('Faturamento Total', ascending=False)
    )

In [36]:
print(faturamento_por_pagamento)

           Pagamento  Faturamento Total
0  Cartão de Crédito        25284699.37
1  Transferência/PIX        14829645.59